[package]
name = "timer_jobs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canister_time = { path = "../canister_time" }
ic-cdk = { version = "0.6.8", features = ["timers"] }
serde = "1.0.152"
